package main

var workTitles = map[string]bool{
	"THE SONNETS":                              true,
	"ALL’S WELL THAT ENDS WELL":                true,
	"THE TRAGEDY OF ANTONY AND CLEOPATRA":      true,
	"AS YOU LIKE IT":                           true,
	"THE COMEDY OF ERRORS":                     true,
	"THE TRAGEDY OF CORIOLANUS":                true,
	"CYMBELINE":                                true,
	"THE TRAGEDY OF HAMLET, PRINCE OF DENMARK": true,
	"THE FIRST PART OF KING HENRY THE FOURTH":  true,
	"THE SECOND PART OF KING HENRY THE FOURTH": true,
	"THE LIFE OF KING HENRY THE FIFTH":         true,
	"THE FIRST PART OF HENRY THE SIXTH":        true,
	"THE SECOND PART OF KING HENRY THE SIXTH":  true,
	"THE THIRD PART OF KING HENRY THE SIXTH":   true,
	"KING HENRY THE EIGHTH":                    true,
	"KING JOHN":                                true,
	"THE TRAGEDY OF JULIUS CAESAR":             true,
	"THE TRAGEDY OF KING LEAR":                 true,
	"LOVE’S LABOUR’S LOST":                     true,
	"THE TRAGEDY OF MACBETH":                   true,
	"MEASURE FOR MEASURE":                      true,
	"THE MERCHANT OF VENICE":                   true,
	"THE MERRY WIVES OF WINDSOR":               true,
	"A MIDSUMMER NIGHT’S DREAM":                true,
	"MUCH ADO ABOUT NOTHING":                   true,
	"THE TRAGEDY OF OTHELLO, MOOR OF VENICE":   true,
	"PERICLES, PRINCE OF TYRE":                 true,
	"KING RICHARD THE SECOND":                  true,
	"KING RICHARD THE THIRD":                   true,
	"THE TRAGEDY OF ROMEO AND JULIET":          true,
	"THE TAMING OF THE SHREW":                  true,
	"THE TEMPEST":                              true,
	"THE LIFE OF TIMON OF ATHENS":              true,
	"THE TRAGEDY OF TITUS ANDRONICUS":          true,
	"THE HISTORY OF TROILUS AND CRESSIDA":      true,
	"TWELFTH NIGHT; OR, WHAT YOU WILL":         true,
	"THE TWO GENTLEMEN OF VERONA":              true,
	"THE TWO NOBLE KINSMEN":                    true,
	"THE WINTER’S TALE":                        true,
	"A LOVER’S COMPLAINT":                      true,
	"THE PASSIONATE PILGRIM":                   true,
	"THE PHOENIX AND THE TURTLE":               true,
	"THE RAPE OF LUCRECE":                      true,
	"VENUS AND ADONIS":                         true,
}

var stopWords = map[string]bool{
	"a":     true,
	"about": true,
	"an":    true,
	"are":   true,
	"as":    true,
	"at":    true,
	"be":    true,
	"by":    true,
	"en":    true,
	"for":   true,
	"from":  true,
	"how":   true,
	"i":     true,
	"in":    true,
	"is":    true,
	"it":    true,
	"la":    true,
	"of":    true,
	"on":    true,
	"or":    true,
	"that":  true,
	"the":   true,
	"this":  true,
	"to":    true,
	"was":   true,
	"what":  true,
	"when":  true,
	"where": true,
	"who":   true,
	"will":  true,
	"with":  true,
}
